---

# task for {{cookiecutter.role_name}}

{% raw %}
- name: include os specific variables
    name: "{{ item }}"
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}.yaml"
   - "{{ ansible_os_family }}.yaml"
   - "main.yaml"
- debug: var=foo
{% endraw %}
