---
# task for {{cookiecutter.role_name}}

- include: install.d/CentOS.yaml
  when: ansible_distribution == "CentOS"
  tags:
    - {{cookiecutter.short_role_name}}

- include: install.d/Ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  tags:
    - {{cookiecutter.short_role_name}}