---
# environment file for {{cookiecutter.role_name}}

- name: Create files {{cookiecutter.short_role_name}}
  sudo: yes
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
  with_items: _{{cookiecutter.short_role_name}}_create_files
  when: _{{cookiecutter.short_role_name}}_create_files is defined
  tag: {{cookiecutter.short_role_name}}
